/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package commision;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author kip
 */
public class NewClass extends javax.swing.JFrame {
String[] Arg = null;
    /**
     * Creates new form home
     */
    public NewClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        units = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee name");

        jLabel2.setText("Employee Grade");

        jLabel3.setText("Employee Units");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(grade)
                            .addComponent(units, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton1)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addComponent(units, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        calculate();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
                
                
               
            }
        });
    }
     public  int  calculate() {
          
                
         int CommisionA=100;
         int  CommisionB=200;
          String nam=name.getText();
           String grad=grade.getText();
          String unit=units.getText();
          Arg[1] = nam;
             Arg[2] =grad;
                Arg[3] = unit;
                   Arg[4] = null;
          
               //System.out.println(unit); 
           int unites= Integer.parseInt(unit);
            int k = unites/20;
          if("A".equals(grad)){
             
     
           if(k>1)
           {
              
               
                 System.out.println(k);   
               int  total_Comm =unites*CommisionA;
              
               int bonus=k*1000;
               int Total_Pay=bonus+ total_Comm;
               int tax=  tax(Total_Pay);
                
                int net_pay=Total_Pay-tax;
                System.out.println(net_pay);
                /* if()
                 {
                     
                 }*/
           
           }
     }
       if("B".equals(grad)){
      
           if(k>1)
           {
              
               
                   
                  int  total_Comm =unites*CommisionB;
                   
                   int bonus=k*1000;
               int Total_Pay=bonus+ total_Comm;
             int tax=tax(Total_Pay);
                int net_pay=Total_Pay-tax;
                System.out.println("Net pay"+net_pay);
              
            
                /* if()
                 {
                     
                 }*/
           
           }
     }
        return 0;
         
     
     }

        public  int  tax(int totalpay) {
            int tax1=0;
            int tax2=0;
            int tax3=0;
            int tax4=0;
            int tax5=0;
            int tot = 0;
            if(totalpay <= 10000)
            {
               tax1= 0;
               tot=totalpay-10000;
                 //  System.out.println(tax1);
                 return tax1;
            }
             if(totalpay <= 20000)
            {
                 tot=totalpay-10000;
                int tax=tax1+(totalpay-10000)*10/100; 
                 tax2=tax;
                // System.out.println(tot);
                 return  tax2;
            }
              if(totalpay <= 30000)
            {
                  tot=totalpay-10000;
                int tax=tax2+(totalpay-10000)*16/100; 
                  tax3= tax;
               //   System.out.println(tot);
                 return tax3;
            }
                      if(totalpay <= 40000)
            {
                  tot=totalpay-10000;
                    int tax=tax3+(totalpay-10000)*22/100; 
                  tax4= tax;
               //   System.out.println(tot);
                 return tax4;
            }
               if(tot > 0)
            {
                
                    int tax=tot*26/100; 
                    tax5=tax4+(tot)*22/100; 
                 
                 // System.out.println(tot);
                 return tax5;
            }
               
          
            
        return 0;
        
        }
    // Variables declaration - do not modify                     
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField units;
    // End of variables declaration                   
}
